<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" retried="2" total="7" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29026" started-at="2020-05-17T02:00:04 IST" finished-at="2020-05-17T02:00:33 IST">
    <groups>
    </groups>
    <test name="ChromeBrowser" duration-ms="29026" started-at="2020-05-17T02:00:04 IST" finished-at="2020-05-17T02:00:33 IST">
      <class name="org.devlab.ui.testbed.RegistrationTest">
        <test-method status="PASS" signature="initDriver(java.lang.String)[pri:0, instance:org.devlab.ui.testbed.RegistrationTest@68bbe345]" name="initDriver" is-config="true" duration-ms="9035" started-at="2020-05-17T02:00:04 IST" finished-at="2020-05-17T02:00:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="register_user_with_valid_setof_data()[pri:0, instance:org.devlab.ui.testbed.RegistrationTest@68bbe345]" name="register_user_with_valid_setof_data" duration-ms="3415" started-at="2020-05-17T02:00:13 IST" finished-at="2020-05-17T02:00:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register_user_with_valid_setof_data -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:org.devlab.ui.testbed.RegistrationTest@68bbe345]" name="teardown" is-config="true" duration-ms="674" started-at="2020-05-17T02:00:17 IST" finished-at="2020-05-17T02:00:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=register_user_with_valid_setof_data status=SUCCESS method=RegistrationTest.register_user_with_valid_setof_data()[pri:0, instance:org.devlab.ui.testbed.RegistrationTest@68bbe345] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- org.devlab.ui.testbed.RegistrationTest -->
      <class name="org.devlab.ui.testbed.LoginTest">
        <test-method status="PASS" signature="beforeSuiteExc()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="beforeSuiteExc" is-config="true" duration-ms="24" started-at="2020-05-17T02:00:04 IST" finished-at="2020-05-17T02:00:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuiteExc -->
        <test-method status="PASS" signature="initDriver(java.lang.String)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="initDriver" is-config="true" duration-ms="9799" started-at="2020-05-17T02:00:04 IST" finished-at="2020-05-17T02:00:14 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="initDriver(java.lang.String)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="initDriver" is-config="true" duration-ms="9060" started-at="2020-05-17T02:00:04 IST" finished-at="2020-05-17T02:00:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="Login_with_with_set_of_valid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="Login_with_with_set_of_valid_data" duration-ms="2939" started-at="2020-05-17T02:00:13 IST" finished-at="2020-05-17T02:00:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_with_set_of_valid_data -->
        <test-method status="SKIP" signature="Login_with_with_set_of_Invalid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="Login_with_with_set_of_Invalid_data" duration-ms="2392" retried="true" started-at="2020-05-17T02:00:14 IST" finished-at="2020-05-17T02:00:16 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login into application with valid set of user :StageUser:StagePwd expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login into application with valid set of user :StageUser:StagePwd expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.devlab.ui.testbed.LoginTest.Login_with_with_set_of_Invalid_data(LoginTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_with_set_of_Invalid_data -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="teardown" is-config="true" duration-ms="1007" started-at="2020-05-17T02:00:16 IST" finished-at="2020-05-17T02:00:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_with_with_set_of_valid_data status=SUCCESS method=LoginTest.Login_with_with_set_of_valid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="teardown" is-config="true" duration-ms="937" started-at="2020-05-17T02:00:16 IST" finished-at="2020-05-17T02:00:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_with_with_set_of_Invalid_data status=SKIP method=LoginTest.Login_with_with_set_of_Invalid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="initDriver(java.lang.String)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="initDriver" is-config="true" duration-ms="4812" started-at="2020-05-17T02:00:17 IST" finished-at="2020-05-17T02:00:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="SKIP" signature="Login_with_with_set_of_Invalid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="Login_with_with_set_of_Invalid_data" duration-ms="2259" retried="true" started-at="2020-05-17T02:00:22 IST" finished-at="2020-05-17T02:00:24 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login into application with valid set of user :StageUser:StagePwd expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login into application with valid set of user :StageUser:StagePwd expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.devlab.ui.testbed.LoginTest.Login_with_with_set_of_Invalid_data(LoginTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_with_set_of_Invalid_data -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="teardown" is-config="true" duration-ms="869" started-at="2020-05-17T02:00:24 IST" finished-at="2020-05-17T02:00:25 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_with_with_set_of_Invalid_data status=SKIP method=LoginTest.Login_with_with_set_of_Invalid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="initDriver(java.lang.String)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="initDriver" is-config="true" duration-ms="4539" started-at="2020-05-17T02:00:25 IST" finished-at="2020-05-17T02:00:30 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="FAIL" signature="Login_with_with_set_of_Invalid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="Login_with_with_set_of_Invalid_data" duration-ms="2191" started-at="2020-05-17T02:00:30 IST" finished-at="2020-05-17T02:00:32 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login into application with valid set of user :StageUser:StagePwd expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login into application with valid set of user :StageUser:StagePwd expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.devlab.ui.testbed.LoginTest.Login_with_with_set_of_Invalid_data(LoginTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_with_set_of_Invalid_data -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="teardown" is-config="true" duration-ms="1199" started-at="2020-05-17T02:00:32 IST" finished-at="2020-05-17T02:00:33 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_with_with_set_of_Invalid_data status=FAILURE method=LoginTest.Login_with_with_set_of_Invalid_data()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="afterSuiteMethod()[pri:0, instance:org.devlab.ui.testbed.LoginTest@a7e666]" name="afterSuiteMethod" is-config="true" duration-ms="2" started-at="2020-05-17T02:00:33 IST" finished-at="2020-05-17T02:00:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuiteMethod -->
      </class> <!-- org.devlab.ui.testbed.LoginTest -->
    </test> <!-- ChromeBrowser -->
  </suite> <!-- Suite -->
</testng-results>
